// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1aFwVv2xuKM2rXlVuMFUUk_7wTQ7-Rrw',
    appId: '1:157000241824:web:a0dfbe381364e19cc42fc5',
    messagingSenderId: '157000241824',
    projectId: 'memecloud-87344',
    authDomain: 'memecloud-87344.firebaseapp.com',
    storageBucket: 'memecloud-87344.appspot.com',
    measurementId: 'G-QXTT1QRXFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-UuCXNN2phDxfqgRmAl8ZL_KAlGQNZ5c',
    appId: '1:157000241824:android:e181fd940ca21a9bc42fc5',
    messagingSenderId: '157000241824',
    projectId: 'memecloud-87344',
    storageBucket: 'memecloud-87344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBynEjEpKRZeBaPauA-GfTRsxL-kjKoWy0',
    appId: '1:157000241824:ios:2921a21fb91f9dd8c42fc5',
    messagingSenderId: '157000241824',
    projectId: 'memecloud-87344',
    storageBucket: 'memecloud-87344.appspot.com',
    iosClientId: '157000241824-ocbs59br39gbhpa5clnpvk543kpq5eqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.memeCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBynEjEpKRZeBaPauA-GfTRsxL-kjKoWy0',
    appId: '1:157000241824:ios:2921a21fb91f9dd8c42fc5',
    messagingSenderId: '157000241824',
    projectId: 'memecloud-87344',
    storageBucket: 'memecloud-87344.appspot.com',
    iosClientId: '157000241824-ocbs59br39gbhpa5clnpvk543kpq5eqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.memeCloud',
  );
}
